services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: zpantry-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: zpantry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "15433:5432"

    volumes:
      - zpantry_postgres_data:/var/lib/postgresql/data

volumes:
  zpantry_postgres_data:
