package com.zpantry.recipe.service;import static com.zpantry.recipe.api.RecipeDtos.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.zpantry.common.api.*;import com.zpantry.ingredient.persistence.IngredientRepository;import com.zpantry.integration.ai.AiClient;import com.zpantry.media.service.MediaStoragePort;import com.zpantry.recipe.domain.*;import com.zpantry.recipe.persistence.*;import java.time.Instant;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class RecipeService{private final RecipeRepository recipes;private final RecipeIngredientRepository links;private final IngredientRepository ingredients;private final AiClient ai;private final MediaStoragePort media;private final ObjectMapper json=new ObjectMapper();public RecipeService(RecipeRepository r,RecipeIngredientRepository l,IngredientRepository i,AiClient a,MediaStoragePort m){recipes=r;links=l;ingredients=i;ai=a;media=m;}private static<T>ApiResponse<T>ok(T d,String m){return new ApiResponse<>(true,m,d,null,"",Instant.now());}private static<T>ApiResponse<T>fail(String m){return new ApiResponse<>(false,m,null,null,"",Instant.now());}
 public PagedResponse<RecipeResponse>list(int pi,int ps){pi=Math.max(1,pi);ps=ps<=0?10:Math.min(ps,100);var p=recipes.findAllByDeletedFalse(PageRequest.of(pi-1,ps,Sort.by("name")));return PagedResponse.successPage(p.stream().map(this::dto).toList(),pi,ps,(int)p.getTotalElements(),"","",Instant.now());}
 public ApiResponse<RecipeResponse>get(UUID id){var e=recipes.findByIdAndDeletedFalse(id).orElse(null);return e==null?fail("Recipe not found."):ok(dto(e),"");}
 @Transactional public ApiResponse<RecipeResponse>create(RecipeRequest r){if(r.name()==null||r.name().isBlank())return fail("Recipe name is required.");RecipeEntity e=new RecipeEntity(r.name());apply(e,r);e=recipes.save(e);replaceLinks(e,r.ingredients()==null?List.of():r.ingredients());embed(e,r.ingredients());return ok(dto(e),"Recipe created.");}
 @Transactional public ApiResponse<RecipeResponse>update(UUID id,RecipeRequest r){if(r.name()==null||r.name().isBlank())return fail("Recipe name is required.");var e=recipes.findByIdAndDeletedFalse(id).orElse(null);if(e==null)return fail("Recipe not found.");e.name=r.name().trim();apply(e,r);e.touch();replaceLinks(e,r.ingredients()==null?List.of():r.ingredients());embed(e,r.ingredients());return ok(dto(e),"Recipe updated.");}
 @Transactional public ApiResponse<Object>delete(UUID id){var e=recipes.findByIdAndDeletedFalse(id).orElse(null);if(e==null)return fail("Recipe not found.");e.softDelete();links.findAllByRecipeIdAndDeletedFalse(id).forEach(RecipeIngredientEntity::softDelete);return ok(null,"Recipe deleted.");}
 @Transactional public ApiResponse<RecipeResponse>createForm(RecipeFormRequest f){try{List<RecipeIngredientRequest>is=f.ingredientsJson()==null?List.of():json.readValue(f.ingredientsJson(),new TypeReference<>(){});var r=new RecipeRequest(f.name(),f.description(),f.cookingTimeMinutes(),f.difficulty(),f.servingSize(),f.instructionText(),f.imageUrl(),f.sourceType(),f.gradientFrom(),f.gradientTo(),is);var out=create(r);if(out.success()&&f.imageFile()!=null&&!f.imageFile().isEmpty()){var e=recipes.findById(out.data().id()).orElseThrow();e.imageUrl=media.upload(f.imageFile(),"recipes").secureUrl();e.touch();return ok(dto(e),"Recipe created.");}return out;}catch(Exception e){return fail("IngredientsJson is invalid JSON.");}}
 @Transactional public ApiResponse<RecipeResponse>updateForm(UUID id,RecipeFormRequest f){try{var e=recipes.findByIdAndDeletedFalse(id).orElse(null);if(e==null)return fail("Recipe not found.");List<RecipeIngredientRequest>is=f.ingredientsJson()==null?null:json.readValue(f.ingredientsJson(),new TypeReference<>(){});if(f.name()!=null&&!f.name().isBlank())e.name=f.name().trim();if(f.description()!=null)e.description=f.description();if(f.cookingTimeMinutes()!=null)e.cookingTimeMinutes=f.cookingTimeMinutes();if(f.difficulty()!=null)e.difficulty=f.difficulty();if(f.servingSize()!=null)e.servingSize=f.servingSize();if(f.instructionText()!=null)e.instructionText=f.instructionText();if(f.sourceType()!=null)e.sourceType=f.sourceType();if(f.gradientFrom()!=null)e.gradientFrom=f.gradientFrom();if(f.gradientTo()!=null)e.gradientTo=f.gradientTo();if(f.imageUrl()!=null)e.imageUrl=f.imageUrl();if(is!=null){replaceLinks(e,is);embed(e,is);}if(f.imageFile()!=null&&!f.imageFile().isEmpty())e.imageUrl=media.upload(f.imageFile(),"recipes").secureUrl();e.touch();return ok(dto(e),"Recipe updated.");}catch(Exception x){return fail("IngredientsJson is invalid JSON.");}}
 private void apply(RecipeEntity e,RecipeRequest r){e.description=r.description();e.cookingTimeMinutes=r.cookingTimeMinutes();e.difficulty=r.difficulty();e.servingSize=r.servingSize();e.instructionText=r.instructionText();e.imageUrl=r.imageUrl();e.sourceType=r.sourceType();e.gradientFrom=r.gradientFrom();e.gradientTo=r.gradientTo();}
 private void replaceLinks(RecipeEntity e,List<RecipeIngredientRequest>items){links.findAllByRecipeIdAndDeletedFalse(e.getId()).forEach(RecipeIngredientEntity::softDelete);items.forEach(x->links.save(new RecipeIngredientEntity(e.getId(),x.ingredientId(),x.quantity(),x.unit(),x.isRequired(),x.note())));}
 private void embed(RecipeEntity e,List<RecipeIngredientRequest>items){List<String> names=(items==null?List.<RecipeIngredientRequest>of():items).stream().map(RecipeIngredientRequest::ingredientName).filter(Objects::nonNull).toList();ai.embedRecipe(e.getId(),e.name,e.description,names,e.instructionText).ifPresent(v->e.embedding=v);}
 private RecipeResponse dto(RecipeEntity e){var is=links.findAllByRecipeIdAndDeletedFalse(e.getId()).stream().map(x->new RecipeIngredientResponse(x.ingredientId,ingredients.findById(x.ingredientId).map(y->y.name).orElse(null),x.quantity,x.unit,x.required,x.note)).toList();return new RecipeResponse(e.getId(),e.name,e.description,e.cookingTimeMinutes,e.difficulty,e.servingSize,e.instructionText,e.imageUrl,e.sourceType,e.gradientFrom,e.gradientTo,is);}
}
